<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class fcmPatient extends Model
{
    protected $fillable = [
        'patientId',
        'patientCode',
        'lastName',
        'firstName',
        'middleName',
        'dateOfConsult',
        'timeOfConsult',
        'age',
        'sex',
        'nationality',
        'civilstatus',
        'birthday',
        'presentaddress',
        'occupation',
        'religion',
        'bp',
        'pulserate',
        'respirationrate',
        'temperature',
        'weight',
        'height',
        'chiefComplaint',
        'historyillness',
        'allergiesInput',
        'hpn_Input',
        'dm_Input',
        'ptb_Input',
        'asthma_Input',
        'covidFirstDose',
        'covidFirstDoseDate',
        'covidSecondDose',
        'covidSecondDoseDate',
        'covidBoosterDose',
        'covidBoosterDoseDate',
        'otherDetails',
        'father',
        'mother',
        'siblings',
        'spouse',
        'children',
        'smoker_Input',
        'alcohol_Input',
        'lmp',
        'pmp',
        'lsc',
        'fpTechnique',
        'gp',
        'g1',
        'g2',
        'g3',
        'g4',
        'g5',
        'constitutionalSymptoms',
        'skin',
        'ears',
        'noseAndSinuses',
        'mouthAndThroat',
        'neck',
        'respiratorySystem',
        'cardiovascular',
        'git',
        'gut',
        'extremities',
        'nervousSystem',
        'hematopoietic',
        'endocrine',
        'generalSurvey',
        'headExam',
        'faceExam',
        'eyesExam',
        'earsExam',
        'noseExam',
        'neckExam',
        'cardiovascularExam',
        'chestExam',
        'skinExam',
        'extremitiesExam',
        'workingImpression',
        'hypertension',
        'diabetes',
        'icdUmbrella',
        'diagnostics',
        'drugs',
        'diet',
        'disposition',
        'formType'
    ];
    public function attachments(){
        return $this->hasMany('App\Attachment', 'id');
    }

    protected $casts = [
        'pmp' => 'json',
        'constitutionalSymptoms' => 'json',
        'skin' => 'json',
        'ears' => 'json',
        'noseAndSinuses' => 'json',
        'mouthAndThroat' => 'json',
        'neck' => 'json',
        'respiratorySystem' => 'json',
        'cardiovascular' => 'json',
        'git' => 'json',
        'gut' => 'json',
        'extremities' => 'json',
        'nervousSystem' => 'json',
        'hematopoietic' => 'json',
        'endocrine' => 'json',
        'icdUmbrella' => 'json',
    ];

    // You might also want to define relationships or additional methods here if needed
}
